### ISSUE TITLE
Add schedule page

### ISSUE THREAD

**Issue by lukefretwell** [ScanGov/scangov-com#15]
We had a schedule page here: https://scangov.com/schedule/

In cards layout:

```
            {% for item in site.data.schedule.docs %}
              <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 d-flex align-items-stretch">
                <div class="card p-4 text-center m-2">
                  {% if item.icon %}
                    <i class="{{ item.icon }} fa-xl mt-2" aria-label="hidden"></i>
                  {% endif %}
                  <h2 class="h3 mt-3 mb-1">{{ item.title }}</h2>
                  {% if item.description %}
                    <p class="card-text mt-1 mb-4">{{ item.description }}</p>
                  {% endif %}
                  {% if item.link %}
                    <p>
                      <a href="{{ site.baseurl }}{{ item.link }}" class="btn btn-primary stretched-link">Schedule</a>
                    </p>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
```

yaml:

```
docs_list_title: schedule
docs:

- title: Demo
  description: 45-minute ScanGov demo + Q&A
  link: https://calendly.com/scangov/30min
  icon: fa-solid fa-wand-magic-sparkles

- title: Consultation
  description: 30-minute ScanGov advisory session
  link: https://calendly.com/scangov/new-meeting
  icon: fa-solid fa-brain

- title: Chat
  description: 30-minute conversation with ScanGov
  link: https://calendly.com/scangov/scangov-chat
  icon: fa-solid fa-comment
```
